In [1]:
import pandas as pd
from os import path

In [2]:
path_dags = path.dirname(path.realpath('__main.ipynb__')) #Guardo la dirección de este .py
name_un = 'GBUNComahue'
df = pd.read_csv(path_dags.replace('/dags',f'/files/{name_un}_select.csv'))
df

,Unnamed: 0,university,career,inscription_date,first_name,last_name,gender,age,postal_code,location,email,fecha_nacimiento
0,0,UNIV. NACIONAL DEL COMAHUE,DISEÑO INDUSTRIAL,2020-11-20,,MICHELLE HARRIS,F,-1,7261,,MARTINEZJOHN@HOTMAIL.COM,1917-10-13
1,1,UNIV. NACIONAL DEL COMAHUE,CONTADOR PÚBLICO,2020-10-31,,AMANDA HILL,F,-1,8129,,TYLER57@HOTMAIL.COM,1990-04-08
2,2,UNIV. NACIONAL DEL COMAHUE,LICENCIATURA EN CIENCIAS AMBIENTALES,2020-09-04,,JASON MONTES,M,-1,3194,,WBRYANT@HOTMAIL.COM,1925-08-09
3,3,UNIV. NACIONAL DEL COMAHUE,AGRONOMÍA,2021-01-31,,RYAN DAVIS,M,-1,3328,,PATRICIAZAMORA@GMAIL.COM,1934-12-23
4,4,UNIV. NACIONAL DEL COMAHUE,DISEÑO INDUSTRIAL,2020-12-03,,SANDRA BURTON,F,-1,4500,,KLEINLAUREN@GMAIL.COM,1970-02-12
...,...,...,...,...,...,...,...,...,...,...,...,...
2065,2065,UNIV. NACIONAL DEL COMAHUE,LICENCIATURA EN CIENCIA Y TECNOLOGÍA DE ALIMENTOS,2020-12-06,,DAVID SANTANA,M,-1,6317,,REBECCAJOHNSON@HOTMAIL.COM,1918-08-09
2066,2066,UNIV. NACIONAL DEL COMAHUE,ACTUARIO,2020-09-03,,NATALIE GILBERT,F,-1,3134,,COWANJENNIFER@GMAIL.COM,1944-11-05
2067,2067,UNIV. NACIONAL DEL COMAHUE,LICENCIATURA EN KINESIOLOGÍA Y FISIATRÍA,2020-12-02,,JAY ELLIS,M,-1,7305,,SMITHJESSICA@GMAIL.COM,1945-02-20
2068,2068,UNIV. NACIONAL DEL COMAHUE,ARQUITECTURA,2020-12-04,,STEPHEN HARRINGTON,M,-1,6307,,FRANCESMILES@GMAIL.COM,1933-01-02
2069,2069,UNIV. NACIONAL DEL COMAHUE,LICENCIATURA EN ADMINISTRACIÓN,2020-12-22,,CHRISTOPHER BELL,M,-1,1757,,EGALLEGOS@YAHOO.COM,2008-02-07

In [5]:
df.location[0] != ''

True

In [13]:
#Correción de formato de texto
df['university'] = df['university'].str.lower().str.replace('_',' ')
#df['university'] = df['university']
df['career'] = df['career'].str.lower().str.replace('_',' ')
#df['career'] = df['career'].str.replace('_',' ')
df['last_name'] = df['last_name'].str.lower()
df['last_name'] = df['last_name'].str.replace('_',' ')
df['gender'] = df['gender'].str.replace('M','male')
df['gender'] = df['gender'].str.replace('F','female')
df['email'] = df['email'].str.lower()
df

,Unnamed: 0,university,career,inscription_date,first_name,last_name,gender,age,postal_code,location,email,fecha_nacimiento
0,0,universidad del salvador,licenciatura en administración,17-Sep-20,,james gonzalez,male,-1,-1,CORONEL_ISLEÑOS,josephjackson@hotmail.com,08-Mar-42
1,1,universidad del salvador,licenciatura en relaciones del trabajo,01-Oct-20,,christopher russell,male,-1,-1,BELLOCQ,pattersonjeremy@gmail.com,04-Apr-46
2,2,universidad del salvador,licenciatura en ciencias ambientales,29-Sep-20,,monica farley,female,-1,-1,CAÑADA_RICA,maria48@yahoo.com,02-Oct-72
3,3,universidad del salvador,licenciatura en ciencia y tecnología de alimentos,21-Dec-20,,tammy sutton,female,-1,-1,FRANCISCO_MADERO,charles28@hotmail.com,18-Jun-52
4,4,universidad del salvador,licenciatura en terapia ocupacional,15-Jan-21,,sydney price,female,-1,-1,PELLEGRINI,singletonjoshua@yahoo.com,12-Jun-36
...,...,...,...,...,...,...,...,...,...,...,...,...
1899,1899,universidad del salvador,licenciatura en musicoterapia,18-Oct-20,,edward gomez,male,-1,-1,ALDEA_MARIA_LUISA,brownsergio@yahoo.com,28-Jun-08
1900,1900,universidad del salvador,actuario,04-Sep-20,,stacey meyer,female,-1,-1,LA_SARA,ganthony@yahoo.com,23-Sep-79
1901,1901,universidad del salvador,licenciatura en producción de bioimagenes,20-Nov-20,,chad kelley,male,-1,-1,SAN_JOSE,gharris@hotmail.com,22-Sep-91
1902,1902,universidad del salvador,licenciatura en ciencia política,11-Sep-20,,bryce navarro,male,-1,-1,ASCENCION,brownsydney@hotmail.com,02-Apr-70
1903,1903,universidad del salvador,bioquímica,07-Nov-20,,ricardo morris,male,-1,-1,BONIFACIO,qdudley@hotmail.com,20-Jan-62

In [21]:
df.inscription_date[:50]

0     17-Sep-20
1     01-Oct-20
2     29-Sep-20
3     21-Dec-20
4     15-Jan-21
5     21-Nov-20
6     02-Nov-20
7     10-Dec-20
8     28-Dec-20
9     29-Sep-20
10    13-Dec-20
11    03-Sep-20
12    29-Nov-20
13    23-Sep-20
14    18-Sep-20
15    06-Jan-21
16    15-Sep-20
17    23-Jan-21
18    30-Oct-20
19    13-Sep-20
20    22-Oct-20
21    02-Sep-20
22    28-Jan-21
23    01-Feb-21
24    13-Oct-20
25    14-Oct-20
26    03-Jan-21
27    02-Oct-20
28    20-Sep-20
29    03-Sep-20
30    05-Oct-20
31    25-Dec-20
32    21-Sep-20
33    14-Oct-20
34    07-Jan-21
35    30-Dec-20
36    08-Jan-21
37    24-Dec-20
38    27-Jan-21
39    03-Sep-20
40    16-Jan-21
41    28-Nov-20
42    13-Oct-20
43    08-Nov-20
44    22-Oct-20
45    29-Dec-20
46    01-Sep-20
47    25-Sep-20
48    05-Oct-20
49    28-Nov-20
Name: inscription_date, dtype: object

In [ ]:
df['age'] = pd.to_datetime(df.inscription_date) - pd.to_datetime(df.fecha_nacimiento)
df['age']=df.age.astype(int)
df['age'] = (df.age / (10**9) / 3600 / 24 /365.2425).astype(int)

In [ ]:
pd.to_datetime(df.fecha_nacimiento).sort_values()

In [ ]:
df.age.describe()

In [ ]:
df2 = pd.read_csv(path_dags.replace('/dags',f'/assets/codigos_postales.csv'))
df2.localidad = df2.localidad.str.lower()
df2

In [ ]:
count = 0
for x in df.postal_code:
    index_df2 = df2.index[df2['codigo_postal'] == x][0]
    df.location[count] = df2.localidad[index_df2]
    count = count + 1
df

In [ ]:
df = df.drop(['Unnamed: 0','fecha_nacimiento'], axis=1)
df

In [ ]:
with open(path_dags.replace('/dags',f'/datasets/{name_un}_process.txt'), 'a') as f:
    dfAsString = df.to_string(header=True, index=False)
    f.write(dfAsString)
    f.close()