In [207]:
import pandas as pd
from os import path

In [208]:
path_dags = path.dirname(path.realpath('__main.ipynb__')) #Guardo la dirección de este .py
name_un = 'GBUNComahue'
df = pd.read_csv(path_dags.replace('/dags',f'/files/{name_un}_select.csv'))

#Correción de formato de texto
df['university'] = df['university'].str.lower()
df['university'] = df['university'].str.replace('_',' ')
df['career'] = df['career'].str.lower()
df['career'] = df['career'].str.replace('_',' ')
df['last_name'] = df['last_name'].str.lower()
df['last_name'] = df['last_name'].str.replace('_',' ')
df['gender'] = df['gender'].str.replace('M','male')
df['gender'] = df['gender'].str.replace('F','female')
df['email'] = df['email'].str.lower()
df

,Unnamed: 0,university,career,inscription_date,first_name,last_name,gender,age,postal_code,location,email,fecha_nacimiento
0,0,univ. nacional del comahue,diseño industrial,2020-11-20,,michelle harris,female,-1,7261,,martinezjohn@hotmail.com,1917-10-13
1,1,univ. nacional del comahue,contador público,2020-10-31,,amanda hill,female,-1,8129,,tyler57@hotmail.com,1990-04-08
2,2,univ. nacional del comahue,licenciatura en ciencias ambientales,2020-09-04,,jason montes,male,-1,3194,,wbryant@hotmail.com,1925-08-09
3,3,univ. nacional del comahue,agronomía,2021-01-31,,ryan davis,male,-1,3328,,patriciazamora@gmail.com,1934-12-23
4,4,univ. nacional del comahue,diseño industrial,2020-12-03,,sandra burton,female,-1,4500,,kleinlauren@gmail.com,1970-02-12
...,...,...,...,...,...,...,...,...,...,...,...,...
2065,2065,univ. nacional del comahue,licenciatura en ciencia y tecnología de alimentos,2020-12-06,,david santana,male,-1,6317,,rebeccajohnson@hotmail.com,1918-08-09
2066,2066,univ. nacional del comahue,actuario,2020-09-03,,natalie gilbert,female,-1,3134,,cowanjennifer@gmail.com,1944-11-05
2067,2067,univ. nacional del comahue,licenciatura en kinesiología y fisiatría,2020-12-02,,jay ellis,male,-1,7305,,smithjessica@gmail.com,1945-02-20
2068,2068,univ. nacional del comahue,arquitectura,2020-12-04,,stephen harrington,male,-1,6307,,francesmiles@gmail.com,1933-01-02
2069,2069,univ. nacional del comahue,licenciatura en administración,2020-12-22,,christopher bell,male,-1,1757,,egallegos@yahoo.com,2008-02-07

In [209]:
df['age'] = pd.to_datetime(df.inscription_date) - pd.to_datetime(df.fecha_nacimiento)
df['age']=df.age.astype(int)
df['age'] = (df.age / (10**9) / 3600 / 24 /365.2425).astype(int)

In [210]:
pd.to_datetime(df.fecha_nacimiento).sort_values()

640    1905-11-21
1166   1905-12-16
1786   1905-12-20
1986   1906-01-11
683    1906-01-19
          ...
872    2021-07-09
820    2021-07-22
832    2021-09-23
812    2021-10-26
241    2021-11-02
Name: fecha_nacimiento, Length: 2070, dtype: datetime64[ns]

In [211]:
df.age.describe()

count    2070.000000
mean       56.564734
std        33.853627
min        -1.000000
25%        27.000000
50%        56.000000
75%        86.000000
max       115.000000
Name: age, dtype: float64

In [212]:
df2 = pd.read_csv(path_dags.replace('/dags',f'/assets/codigos_postales.csv'))
df2.localidad = df2.localidad.str.lower()
df2

      codigo_postal                     localidad
0              1601            isla martin garcia
1              1602                       florida
2              1603                villa martelli
3              1605                    carapachay
4              1607                 villa adelina
...             ...                           ...
1515           9409             isla gran malvina
1516           9410                bahia lapataia
1517           9411  base aerea teniente matienzo
1518           9420             aserradero arroyo
1519           9421               frigorifico cap

[1520 rows x 2 columns]

In [213]:
count = 0
for x in df.postal_code:
    index_df2 = df2.index[df2['codigo_postal'] == x][0]
    df.location[count] = df2.localidad[index_df2]
    count = count + 1
df

/tmp/ipykernel_3161/413148739.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.location[count] = df2.localidad[index_df2]

,Unnamed: 0,university,career,inscription_date,first_name,last_name,gender,age,postal_code,location,email,fecha_nacimiento
0,0,univ. nacional del comahue,diseño industrial,2020-11-20,,michelle harris,female,103,7261,saladillo norte,martinezjohn@hotmail.com,1917-10-13
1,1,univ. nacional del comahue,contador público,2020-10-31,,amanda hill,female,30,8129,17 de agosto,tyler57@hotmail.com,1990-04-08
2,2,univ. nacional del comahue,licenciatura en ciencias ambientales,2020-09-04,,jason montes,male,95,3194,paso telegrafo,wbryant@hotmail.com,1925-08-09
3,3,univ. nacional del comahue,agronomía,2021-01-31,,ryan davis,male,86,3328,colonia japonesa,patriciazamora@gmail.com,1934-12-23
4,4,univ. nacional del comahue,diseño industrial,2020-12-03,,sandra burton,female,50,4500,alto del saladillo,kleinlauren@gmail.com,1970-02-12
...,...,...,...,...,...,...,...,...,...,...,...,...
2065,2065,univ. nacional del comahue,licenciatura en ciencia y tecnología de alimentos,2020-12-06,,david santana,male,102,6317,la florencia,rebeccajohnson@hotmail.com,1918-08-09
2066,2066,univ. nacional del comahue,actuario,2020-09-03,,natalie gilbert,female,75,3134,antonio tomas sud,cowanjennifer@gmail.com,1944-11-05
2067,2067,univ. nacional del comahue,licenciatura en kinesiología y fisiatría,2020-12-02,,jay ellis,male,75,7305,antonio de los heros,smithjessica@gmail.com,1945-02-20
2068,2068,univ. nacional del comahue,arquitectura,2020-12-04,,stephen harrington,male,87,6307,colonia la oracion,francesmiles@gmail.com,1933-01-02
2069,2069,univ. nacional del comahue,licenciatura en administración,2020-12-22,,christopher bell,male,12,1757,gregorio de laferrere,egallegos@yahoo.com,2008-02-07

In [214]:
df = df.drop(['Unnamed: 0','fecha_nacimiento'], axis=1)
df

,university,career,inscription_date,first_name,last_name,gender,age,postal_code,location,email
0,univ. nacional del comahue,diseño industrial,2020-11-20,,michelle harris,female,103,7261,saladillo norte,martinezjohn@hotmail.com
1,univ. nacional del comahue,contador público,2020-10-31,,amanda hill,female,30,8129,17 de agosto,tyler57@hotmail.com
2,univ. nacional del comahue,licenciatura en ciencias ambientales,2020-09-04,,jason montes,male,95,3194,paso telegrafo,wbryant@hotmail.com
3,univ. nacional del comahue,agronomía,2021-01-31,,ryan davis,male,86,3328,colonia japonesa,patriciazamora@gmail.com
4,univ. nacional del comahue,diseño industrial,2020-12-03,,sandra burton,female,50,4500,alto del saladillo,kleinlauren@gmail.com
...,...,...,...,...,...,...,...,...,...,...
2065,univ. nacional del comahue,licenciatura en ciencia y tecnología de alimentos,2020-12-06,,david santana,male,102,6317,la florencia,rebeccajohnson@hotmail.com
2066,univ. nacional del comahue,actuario,2020-09-03,,natalie gilbert,female,75,3134,antonio tomas sud,cowanjennifer@gmail.com
2067,univ. nacional del comahue,licenciatura en kinesiología y fisiatría,2020-12-02,,jay ellis,male,75,7305,antonio de los heros,smithjessica@gmail.com
2068,univ. nacional del comahue,arquitectura,2020-12-04,,stephen harrington,male,87,6307,colonia la oracion,francesmiles@gmail.com
2069,univ. nacional del comahue,licenciatura en administración,2020-12-22,,christopher bell,male,12,1757,gregorio de laferrere,egallegos@yahoo.com

In [215]:
with open(path_dags.replace('/dags',f'/datasets/{name_un}_process.txt'), 'a') as f:
    dfAsString = df.to_string(header=True, index=False)
    f.write(dfAsString)
    f.close()